local Framework = game:GetService("ReplicatedStorage"):WaitForChild("Framework")
require(Framework.FrameworkInit)
require(script.Parent.Framework.FServer)
require(script.Parent.Service.FrameworkService):Init()
print("[Roblox_Y1] 服务端框架已启动")
